version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependency update"
    default_assignees:
      - "luzfcb"
  - package_manager: "python"
    directory: "/{{cookiecutter.project_slug}}/requirements"
    update_schedule: "weekly"
    default_labels:
      - "dependency update"
    default_assignees:
      - "luzfcb"
